version: '3'
services:
  app-node:
    image: svelte-docker-node
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy-app
    image: mol-frontend:dev
    ports:
      - 3002:3000
